apiVersion: apps/v1
kind: Deployment
metadata:
  name: Python-image
  labels:
    app: python
  annotations:
    kubernetes.io/change-cause: "python_image_one"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: my-container
        image: sirisha1202/pythonimage1
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
