apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx-con
    image: nginx
    envFrom:
        - configMapRef:
            name: myconfigmap