apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-con
        image: sirisha1202/blue_deploy_image
        ports:
        - containerPort: 80