apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    name: pod
spec:
  containers:
  - name: app-con
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:                
        name: secret