apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-con
        image: sirisha1202/blue_deploy_image
        ports:
        - containerPort: 80